[theme]
primaryColor = "#111827"         # dark gray for active buttons
backgroundColor = "#F5F7FB"      # soft gray background
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
runOnSave = true
headless = true
